# Generated by Django 5.2.6 on 2026-02-26 16:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_completos', models.CharField(default='', max_length=50, verbose_name='Nombres Completos')),
                ('correo_electronico', models.EmailField(default='', max_length=50, verbose_name='Correo Electrónico')),
                ('contrasena', models.CharField(default='', max_length=128, verbose_name='Contraseña')),
                ('cedula', models.CharField(default='', max_length=20, verbose_name='Cédula')),
                ('telefono', models.CharField(default='', max_length=15, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=80, unique=True, verbose_name='Nombre Categoría')),
                ('descripcion', models.TextField(max_length=110, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='GestionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('categoria', models.CharField(default='Capacitación', max_length=50, verbose_name='Categoría (Badge)')),
                ('imagen', models.ImageField(upload_to='servicios/', verbose_name='Imagen Principal')),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Actual')),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio Antes (Opcional)')),
                ('descuento', models.IntegerField(default=0, verbose_name='Porcentaje OFF (Opcional)')),
                ('descripcion_breve', models.TextField(max_length=300, verbose_name='Descripción Corta (Para tarjetas)')),
                ('descripcion_detallada', models.TextField(verbose_name='Descripción Completa (Detalle)')),
                ('duracion', models.CharField(max_length=50, verbose_name='Duración (Ej: 8 horas)')),
                ('modalidad', models.CharField(default='Virtual en vivo', max_length=50, verbose_name='Modalidad')),
                ('incluye_certificado', models.BooleanField(default=True, verbose_name='¿Incluye Certificado?')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Servicio Activo?')),
                ('destacado', models.BooleanField(default=False, verbose_name='¿Mostrar en inicio?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=80, unique=True, verbose_name='Nombre Marca')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('logo_marca', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('color', models.CharField(max_length=25, verbose_name='Color')),
                ('modelo', models.CharField(max_length=25, verbose_name='Modelo')),
                ('funcion_principal', models.CharField(max_length=100, verbose_name='Función Principal')),
                ('descripcion', models.CharField(max_length=65, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Presentación',
                'verbose_name_plural': 'Tipos de Presentación',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento_nit', models.CharField(max_length=15, unique=True)),
                ('direccion_empresa', models.CharField(max_length=150)),
                ('numero_telefonico', models.CharField(max_length=15)),
                ('descripcion', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField(verbose_name='Fecha Factura')),
                ('descripcion_venta', models.TextField(max_length=255, verbose_name='Descripción Venta')),
                ('terminos_condiciones', models.TextField(max_length=255, verbose_name='Términos y Condiciones')),
                ('nit', models.CharField(max_length=50, verbose_name='NIT')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_admin', to='mi_app.administrador')),
                ('id_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_servicio', to='mi_app.gestionservicio')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_garantia', models.TextField(max_length=255, verbose_name='Descripción Garantía')),
                ('fecha_garantia', models.DateField(verbose_name='Fecha Garantía')),
                ('estado_garantia', models.CharField(choices=[('PENDIENTE', 'pendiente'), ('APROVADO', 'aprovado'), ('RECHAZADO', 'rechazado')], max_length=20)),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garantias_factura', to='mi_app.factura')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
            },
        ),
        migrations.CreateModel(
            name='GestionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('numero_telefonico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Telefónico')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número Documento')),
                ('correo_electronico', models.EmailField(max_length=50, verbose_name='Correo Electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_producto', models.ImageField(blank=True, null=True, upload_to='producto/', verbose_name='Logo producto')),
                ('cantidad_producto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Producto')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Unitario')),
                ('estado_producto', models.CharField(max_length=30, verbose_name='Estado Producto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_categoria', to='mi_app.categoria')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_marca', to='mi_app.marca')),
                ('id_presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_presentacion', to='mi_app.presentacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento_entrega', models.CharField(max_length=50)),
                ('municipio_ciudad_entrega', models.CharField(max_length=50)),
                ('direccion_entrega', models.CharField(max_length=50)),
                ('comprobante_pago', models.CharField(default='pago exitoso', max_length=50)),
                ('estado_pedido', models.CharField(choices=[('PROCESO', 'proceso'), ('PEDIDO EXITOSO', 'pedido exitoso')], max_length=20, verbose_name='Estado Pedido')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to='mi_app.gestioncliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_producto', to='mi_app.producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mi_app.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_productos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Productos')),
                ('observaciones', models.TextField(blank=True, max_length=60, verbose_name='Observaciones')),
                ('fecha_compra', models.DateField(verbose_name='Fecha Compra')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_admin', to='mi_app.administrador')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_producto', to='mi_app.producto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_proveedor', to='mi_app.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
