# Generated by Django 5.2.6 on 2026-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion_empresa',
            field=models.CharField(max_length=150),
        ),
    ]
