# Generated by Django 5.2.6 on 2025-11-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='descripcion',
            field=models.CharField(max_length=65, verbose_name='Descripción'),
        ),
    ]
