# Generated by Django 5.2.6 on 2026-02-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestioncliente',
            name='avatar',
            field=models.CharField(default='avatar1.png', max_length=30, verbose_name='Avatar'),
        ),
    ]
