# Generated by Django 5.2.6 on 2026-02-20 12:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_alter_proveedor_direccion_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestioncliente',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='gestioncliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestioncliente',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
