# Generated by Django 5.2.6 on 2026-03-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_gestioncliente_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestioncliente',
            name='email_pendiente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
