# Generated by Django 5.2.6 on 2025-11-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_presentacion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='logo_producto',
            field=models.ImageField(blank=True, null=True, upload_to='producto/', verbose_name='Logo producto'),
        ),
    ]
