# Generated by Django 5.2.6 on 2026-02-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_remove_gestioncliente_contrasena_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
