# Generated by Django 5.2.6 on 2026-02-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_producto_logo_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre_producto',
        ),
    ]
