# Generated by Django 5.2.6 on 2026-03-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_gestioncliente_email_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='descripcion',
            field=models.CharField(max_length=700, verbose_name='Descripción'),
        ),
    ]
