# Generated by Django 5.2.7 on 2025-10-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_rename_presentaciontipo_presentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='nombre_de_producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
