# Generated by Django 5.2.7 on 2025-10-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_rename_gestionpedido_pedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PresentacionTipo',
            new_name='Presentacion',
        ),
    ]
