# Generated by Django 5.2.7 on 2025-10-15 19:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_rename_presentaciontipo_presentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='email',
        ),
        migrations.AddField(
            model_name='administrador',
            name='contrasena',
            field=models.CharField(default='', max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='correo_electronico',
            field=models.EmailField(default='', max_length=50, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='cedula',
            field=models.CharField(default='', max_length=20, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nombres_completos',
            field=models.CharField(default='', max_length=50, verbose_name='Nombres Completos'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(default='', max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre Categoría'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad_productos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Productos'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(verbose_name='Fecha Compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='observaciones',
            field=models.TextField(blank=True, max_length=60, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='descripcion_venta',
            field=models.TextField(max_length=255, verbose_name='Descripción Venta'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateField(verbose_name='Fecha Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nit',
            field=models.CharField(max_length=50, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='terminos_condiciones',
            field=models.TextField(max_length=255, verbose_name='Términos y Condiciones'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='descripcion_garantia',
            field=models.TextField(max_length=255, verbose_name='Descripción Garantía'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='fecha_garantia',
            field=models.DateField(verbose_name='Fecha Garantía'),
        ),
        migrations.AlterField(
            model_name='gestioncliente',
            name='contrasena',
            field=models.CharField(max_length=50, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='gestioncliente',
            name='correo_electronico',
            field=models.EmailField(max_length=50, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='gestioncliente',
            name='nombre_completo',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='gestioncliente',
            name='numero_documento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número Documento'),
        ),
        migrations.AlterField(
            model_name='gestioncliente',
            name='numero_telefonico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Telefónico'),
        ),
        migrations.AlterField(
            model_name='gestionservicio',
            name='descripcion',
            field=models.TextField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='gestionservicio',
            name='nombre_servicio',
            field=models.CharField(max_length=50, verbose_name='Nombre Servicio'),
        ),
        migrations.AlterField(
            model_name='gestionservicio',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo_marca',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo Marca'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre_marca',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre Marca'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.CharField(default='pago exitoso', max_length=50, verbose_name='Comprobante Pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='departamento_entrega',
            field=models.CharField(max_length=50, verbose_name='Departamento Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(max_length=50, verbose_name='Dirección Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('PROCESO', 'proceso'), ('PEDIDO EXITOSO', 'pedido exitoso')], max_length=20, verbose_name='Estado Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='municipio_ciudad_entrega',
            field=models.CharField(max_length=50, verbose_name='Municipio/Ciudad Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_de_producto',
            field=models.CharField(max_length=50, verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='color',
            field=models.CharField(max_length=25, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='descripcion',
            field=models.CharField(max_length=60, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='funcion_principal',
            field=models.CharField(max_length=100, verbose_name='Función Principal'),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='modelo',
            field=models.CharField(max_length=25, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_producto',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_producto',
            field=models.CharField(max_length=30, verbose_name='Estado Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=100, verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Unitario'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=models.TextField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion_empresa',
            field=models.CharField(max_length=30, verbose_name='Dirección Empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_completo',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_documento_nit',
            field=models.CharField(max_length=15, unique=True, verbose_name='Número Documento NIT'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_telefonico',
            field=models.CharField(max_length=15, verbose_name='Número Telefónico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='comprobante_pago',
            field=models.CharField(max_length=50, verbose_name='Comprobante Pago'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha_venta',
            field=models.DateField(verbose_name='Fecha Venta'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_admin', to='mi_app.administrador', verbose_name='Administrador'),
        ),
    ]
